### ISSUE TITLE
Views doesn't work if the main app's default view engine is not jade

### ISSUE THREAD

**Issue by rawiroaisen** [etabits/node-penguin#1]
Please change 

_render: (req, res, template, locals) =>
  res.render path.resolve(__dirname, '../views/', template), locals

to

_render: (req, res, template, locals) =>
  res.render path.resolve(__dirname, '../views/', template + '.jade'), locals

(added '.jade' suffix)

in file src/index.coffee
in line 314

PS: I don't know how to make pull requests...

**Comment by joejean** [comment]
I'm using nunjucks as my default view engine and when I go to /admin I get a template not found error: "template not found: /home/joe/Documents/chipin/node_modules/penguin/views/index.jade"
I have given all access penguin/views folder. Can you please help me with that issue? Thanks.

**Comment by sogko** [comment]
Hi @joejean 

You can specify the ```templatesPath``` options, for e.g.:
```coffeescript
path = require('path')
penguin = require("penguin")
admin = new penguin.Admin {
  templatesPath: path.resolve(__dirname, '../views/', '%s.html')
}
...
```
Assuming that your nunchucks templates have `.html` extensions and are in `views` folder one level up.
`node-penguin` will replace the `%s` with the name of the required view.

Hope this helps!
