### ISSUE TITLE
When mongoose 4?

### ISSUE THREAD

**Issue by agent-john** [etabits/node-penguin#11]
npm ERR! peerinvalid The package mongoose does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer penguin@0.3.0 wants mongoose@3.8.x

**Comment by ludoo0d0a** [comment]
+1

**Comment by aularon** [comment]
Please fork, try and send a pull request. I do not think it will need many changes.
I am sorry but I am unable to find the time to work on this at this time...

**Comment by aularon** [comment]
Another late word on this issue: I faced a problem with mongodb 3.2.x (which requires mongoose >=4.3.0, see [mongoose compatibility](http://mongoosejs.com/docs/compatibility.html)). I tried installing mongoose 4, and it worked without a problem (although npm complains about unmet peer dependency!)

**Comment by Reedyuk** [comment]
I forked the repo and changed the dependancy and ran it on my local of penguin and it works fine.
https://github.com/etabits/node-penguin/pull/14
You will need to update the penguin example project, as it has a lower version of mongoose, to this
` "mongoose": "4.9.6",`

**Comment by aularon** [comment]
mongoose bumped to 5.x
It should work with 3.x and 4.x as well as it uses very basic API calls
